apiVersion: v1
kind: ServiceAccount
metadata:
  name: argora
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argora
  namespace: default
subjects:
  - kind: ServiceAccount
    name: argora
    namespace: default
roleRef:
    kind: ClusterRole
    name: argora
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argora
  namespace: default
  labels:
    app: argora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argora
  template:
    metadata:
      labels:
        app: argora
    spec:
      serviceAccountName: argora
      containers:
        - name: argora
          image: argora-dev:latest
          args:
            - --controllers="metal3Controller"
          #  - --controllers="ironCoreServerController"
          envFrom:
            - secretRef:
                name: argora
