apiVersion: apps/v1
kind: Deployment
metadata:
  name: argora
  namespace: default
  labels:
    app: argora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argora
  template:
    metadata:
      labels:
        app: argora
    spec:
      containers:
        - name: argora
          image: argora-dev:latest
