# Copyright 2024 SAP SE
# SPDX-License-Identifier: Apache-2.0

version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exptostd
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - gomoddirectives
    - gosec
    - govet
    - ineffassign
    - intrange
    - lll
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: true
    forbidigo:
      forbid:
        - pattern: ^ioutil\..*$
        - pattern: ^http\.DefaultServeMux$
        - pattern: ^http\.Handle(?:Func)?$
        - pkg: ^gopkg\.in/square/go-jose\.v2$
          msg: gopk.in/square/go-jose is archived and has CVEs. Replace it with gopkg.in/go-jose/go-jose.v2
        - pkg: ^github.com/coreos/go-oidc$
          msg: github.com/coreos/go-oidc depends on gopkg.in/square/go-jose which has CVEs. Replace it with github.com/coreos/go-oidc/v3
        - pkg: ^github.com/howeyc/gopass$
          msg: github.com/howeyc/gopass is archived, use golang.org/x/term instead
      analyze-types: true
    goconst:
      min-occurrences: 5
    gocritic:
      enabled-checks:
        - boolExprSimplify
        - builtinShadow
        - emptyStringTest
        - evalOrder
        - httpNoBody
        - importShadow
        - initClause
        - methodExprCall
        - paramTypeCombine
        - preferFilepathJoin
        - ptrToRefParam
        - redundantSprint
        - returnAfterHttpError
        - stringConcatSimplify
        - timeExprSimplify
        - truncateCmp
        - typeAssertChain
        - typeUnparen
        - unnamedResult
        - unnecessaryBlock
        - unnecessaryDefer
        - weakCond
        - yodaStyleExpr
    gomoddirectives:
      replace-allow-list:
        - github.com/mdlayher/arp
      toolchain-forbidden: false
      go-version-pattern: 1\.\d+(\.0)?$
    gosec:
      excludes:
        - G112
        - G306
    govet:
      disable:
        - fieldalignment
      enable-all: true
    nolintlint:
      require-specific: true
    revive:
      rules:
        - name: comment-spacings
        - name: dot-imports
          arguments:
          - allowed-packages: 
            - github.com/onsi/ginkgo/v2
            - github.com/onsi/gomega
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true
      constant-kind: true
    usetesting:
      os-setenv: true
      os-temp-dir: true
    whitespace:
      multi-func: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - bodyclose
          - dupl
        path: _test\.go
      - linters:
          - lll
        path: api/*
      - linters:
          - lll
          - nolintlint
        path: cmd/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - dupword
          - errcheck
          - errorlint
          - gocritic
          - gosec
          - govet
          - nolintlint
          - perfsprint
          - staticcheck
        path: test/*
      - path: (.+)\.go$
        text: declaration of "err" shadows declaration at
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/sapcc/argora
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
