# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "argora"
SPDX-PackageDownloadLocation = "https://github.com/sapcc/argora"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  ".github/**",
  ".gitignore",
  ".dockerignore",
  ".golangci.yml",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
  "Makefile",
  "PROJECT",
  "go.mod",
  "go.sum",
  "config/**",
  "dist/**",
  "docs/**",
  "hack/**",
]
SPDX-FileCopyrightText = "SAP SE"
SPDX-License-Identifier = "Apache-2.0"
