apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  credentials.json: |-
    {
      "netboxUrl": "{{ .Values.netbox.url | b64enc }}",
      "netboxToken": "{{ .Values.netbox.token | b64enc }}",
      "bmcUser": "{{ .Values.bmc.username | b64enc }}",
      "bmcPassword": "{{ .Values.bmc.password | b64enc }}"
    }
