# SPDX-FileCopyrightText: 2025 SAP SE
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  credentials.json: "{{ toJson .Values.credentials }}"
